- hosts: master
  become: yes
  any_errors_fatal: yes
  environment: "{{ k8s_env }}"

  tasks:
    - name: install requried packages
      include_role: 
        name: package

    - name: install NFD for labelling node with zigbee dongle
      include_role:
        name: node-feature-discover
        
    - name: install home-assistant
      include_role:
        name: home-assistant




