- hosts: master
  become: yes
  any_errors_fatal: yes
  environment: "{{ k8s_env }}"

  tasks:
    - name: install requried packages
      include_role: 
        name: package

    - name: install metallb
      include_role:
        name: metallb




