- name: create namespace, pvc
  kubernetes.core.k8s:
    definition: "{{ lookup('file', '{{ item }}') | from_yaml }}"
  loop:
    - namespace.yml
    - pvc.yml


- name: deploy home assistant 
  kubernetes.core.k8s:
    template: "{{ item }}"
  loop:
    - deployment.yml.j2
    - service.yml.j2


