- name: download metallb manifest
  get_url:
    url: "{{ metallb_manifest }}"
    dest: "{{ downloaded_metallb_manifest }}"

- name: "apply {{ downloaded_metallb_manifest }}"
  kubernetes.core.k8s:
    src: "{{ downloaded_metallb_manifest }}"
    state: present
    wait: yes

- name: clean up
  file:
    path: "{{ downloaded_metallb_manifest }}"
    state: absent
