- name: check if memory cgroup is enabled
  command: "awk '/^memory/ { print $4 }' /proc/cgroups"
  register: memory_cgroup

- block:
        
  # Need to backup the file manually due to 
  # ":" in the backup file time format being invalid in /boot which is VFAT filesystem
  - name: backup /boot/cmdline.txt
    copy:
      remote_src: yes
      src: /boot/cmdline.txt
      dest: "/boot/cmdline.txt.{{ ansible_date_time.iso8601_basic_short }}"

  - name: enable memory cgroup in raspbery pi
    replace:
      path: /boot/cmdline.txt
      regexp: '^(.*(?!cgroup_memory=1 cgroup_enable=memory).*)$'
      replace: '\1 cgroup_memory=1 cgroup_enable=memory'

  - reboot:

  when: memory_cgroup.stdout != '1'
