apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
  name: home-assistant-deploy
  namespace: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
          - containerPort: 8123
        volumeMounts:
          - name: configuration
            mountPath: /config
      volumes:
      - name: configuration
        persistentVolumeClaim:
          claimName: home-assistant-pvc
