apiVersion: v1
kind: Service
metadata:
  #labels:
  #  app: home-assistant
  name: home-assistant-service
  namespace: home-assistant
spec:
  ports:
  - port: 80
    targetPort: 8123
  selector:
    app: home-assistant
  type: LoadBalancer
